### ISSUE TITLE
Review the test_lists.py

### ISSUE THREAD

**Issue by leunami420** [htw-imi-info3/python-learning#21]
@everyone please review our beautiful test method! thx alot :)

  _______

**Comment by abductedRhino** [comment]
Nice Test! I hope you like the small changes in [this commit](https://github.com/htw-imi-info3/python-learning/commit/24ec05256e9edaabeae5dcab425505fd2c1e8e5f).
- Change `""` to `''`, as the [python style guide](https://peps.python.org/pep-0008/#string-quotes) recommends to choose one variant and stick with it.
- Rename `test1` to `test_append` for a less generic method name. 
- Add `setUp` method that calls `my_shoppinglist.clear()` [before each test](https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUp) to improve compatibility with future expansions.

**Comment by thexeto** [comment]
Went through test and everything works fine! I didn't change anything.

**Comment by prodmatze** [comment]
Tested and added a print statement to print out the list
